Repository DBDIBABIDIBU/be15-1st-DBDIBABDBU-mobile_receipt, pull requests merged in 2025-02, with the labels that each got.

#1 docs: 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: 📑docs

#2 docs: 이슈 템플릿 양식 변경
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: 📑docs

#6 feat:DDL.sql added
  src/mobile-receipt/ddl/project_ddl.sql
Labels: ✨feature

#9 review, review_image, review_like, comment 테이블에 제약조건 추가
  src/mobile-receipt/ddl/project_ddl.sql
Labels: ✨feature

#14 [DOCS] pull_request_template.md 작성
  .github/pull_request_template.md
Labels: 📑docs

#12 refactor:DDL point 테이블, point_product 테이블 수정
  src/mobile-receipt/ddl/project_ddl.sql
Labels: ♻️refactor

#15 docs: pr template 수정
  .github/pull_request_template.md
Labels: 📑docs

#22 [test] 포인트 관리 테스트 케이스
  src/mobile-receipt/point/diagram_point_exchange.md
  src/mobile-receipt/point/diagram_point_manage.md
  src/mobile-receipt/point/procedure_point_exchange.sql
  src/mobile-receipt/point/procedure_point_manage.sql
  src/mobile-receipt/point/test_case_point_manage.sql
Labels: ✅test

#29 [feature] 비밀번호 변경 기능 구현
  src/mobile-receipt/user/upate_password.sql
Labels: ✨feature

#26 [feature] 회원 탈퇴 기능 구현
  src/user/delete_account.sql
Labels: ✨feature

#25 [feature] 회원 가입 기능 구현
  src/mobile-receipt/user/signup.sql
Labels: ✨feature

#32 [feature] 회원 프로필 수정 기능 구현
  src/mobile-receipt/user/update_profile.sql
Labels: ✨feature

#41 [feature] review CRUD 기능
  src/mobile-receipt/review/review.sql
Labels: ✨feature

#47 [feature] store 관련 생성 / 수정 / 삭제 (삭제 시 리뷰 , 즐겨찾기 deleted_at 입력)
  src/mobile-receipt/store/delete_store.sql
  src/mobile-receipt/store/insert_store.sql
  src/mobile-receipt/store/search_store_category.sql
  src/mobile-receipt/store/search_store_name.sql
  src/mobile-receipt/store/search_store_rating.sql
  src/mobile-receipt/store/update_store.sql
Labels: ✨feature

#52 [refactor] 포인트 관리 테스트 케이스 변경
  src/mobile-receipt/point/diagram_point_exchange.md
  src/mobile-receipt/point/diagram_point_manage.md
  src/mobile-receipt/point/procedure_point_exchange.sql
  src/mobile-receipt/point/procedure_point_manage.sql
  src/mobile-receipt/point/test_case_point_manage.sql
Labels: ♻️refactor

#59 [feature]제제 내역 관련 기능 구현
  src/penalty_history/admin_user_penalty_update.sql
  src/penalty_history/user_penalty_history_select.sql
Labels: ✨feature

#61 [feature]신고 관련 기능 구현
  src/report/admin_user_report_select.sql
  src/report/report_comment.sql
  src/report/report_review.sql
Labels: ✨feature

#64 - 정보 제공에 동의한 유저가 연령별 / 성별에 따른 평균 지출 조회 기능 구현
  src/mobile-receipt/user/etc/age_avg.sql
  src/mobile-receipt/user/etc/category_avg.sql
  src/mobile-receipt/user/etc/compare_monthly_receipt.sql
  src/mobile-receipt/user/etc/gender_avg.sql
Labels: ✨feature

#65 [Feat]: user 관련 남은 기능 구현
  src/mobile-receipt/user/add_favorite.sql
  src/mobile-receipt/user/delete_account.sql
  src/mobile-receipt/user/get_login_history.sql
  src/mobile-receipt/user/get_user_list.sql
  src/mobile-receipt/user/get_user_profile.sql
  src/mobile-receipt/user/login.sql
  src/mobile-receipt/user/remove_favorite.sql
  src/mobile-receipt/user/signup.sql
  src/mobile-receipt/user/update_password.sql
  src/mobile-receipt/user/update_profile.sql
  src/mobile-receipt/user/user_util_procedure.sql
Labels: ✨feature

#68 [hotfix] 영수증과 포인트 관련 로직의 중첩 트랜잭션 문제 해결
  dbconvention.md
  src/mobile-receipt/point/diagram_point_cancel.md
  src/mobile-receipt/point/diagram_point_exchange.md
  src/mobile-receipt/point/diagram_point_use.md
  src/mobile-receipt/point/inquiry_point_history.sql
  src/mobile-receipt/point/old/diagram_point_exchange.md
  src/mobile-receipt/point/old/diagram_point_manage.md
  src/mobile-receipt/point/old/procedure_point_manage.sql
  src/mobile-receipt/point/old/test_case_point_exchange.sql
  src/mobile-receipt/point/old/test_case_point_manage.sql
  src/mobile-receipt/point/procedure_point_exchange.sql
  src/mobile-receipt/point/procedure_point_manage.sql
  src/mobile-receipt/point/sp_common.sql
  src/mobile-receipt/point/sp_point_cancel.sql
  src/mobile-receipt/point/sp_point_earn.sql
  src/mobile-receipt/point/sp_point_exchange.sql
  src/mobile-receipt/point/sp_point_use.sql
  src/mobile-receipt/point/tc_receipt_point_sync.sql
  src/mobile-receipt/receipt/diagram_cancel_receipt.md
  src/mobile-receipt/receipt/diagram_issue_receipt.md
  src/mobile-receipt/receipt/old/insert_receipt.sql
  src/mobile-receipt/receipt/old/purchase_history.sql
  src/mobile-receipt/receipt/old/receipt_cancel_procedure.sql
  src/mobile-receipt/receipt/sp_cancel_receipt.sql
  src/mobile-receipt/receipt/sp_issue_receipt.sql
Labels: 🚑hotfix

#70 [docs] Update README.md
  README.md
Labels: 📑docs

#72 영수증 기간별 조회, 매장명으로 조회, 결제방식으로 조회 등 수행할 수 있는 view 구현
  src/mobile-receipt/receipt/receipt_search_view.sql
Labels: ✨feature

#75 매장별 월별 / 일별 판매량 등 매출 분석 제공
  src/mobile-receipt/store/store_sales_data.sql
Labels: ✨feature

#77 [refactor] 영수증, 포인트 테스트 케이스 시연을 위한 수정
  src/mobile-receipt/point/sp_point_earn.sql
  src/mobile-receipt/point/tc_receipt_point_sync.sql
Labels: ♻️refactor

#82 [hotfix] 태그 수정
  README.md
Labels: 🛠️bugfix, 🚑hotfix

#84 [hotfix] gif 파일이 잘못 등록되어 수정
  assets/test_case_gif/receipt/05_에러_잔여 포인트 초과 물품 구매 시도.gif
Labels: 🚑hotfix
